spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://postgres:5432/development_database}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10  
      connection-timeout: 30000  

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:development}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      username: ${REDIS_USERNAME:default}
      password: ${REDIS_PASSWORD:default}
      database: ${DATABASE_NUM:0}
      timeout: 2000